name: Parse Test Target JSON
description: 'Mocks parsing test targets by returning static list.'

outputs:
  test_targets_json:
    description: "The list of test targets."
    value: ${{ steps.parse.outputs.test_targets_json }}
  test_targets_count:
    description: "The number of test targets."
    value: ${{ steps.parse.outputs.test_targets_count }}

runs:
  using: "composite"
  steps:
    - name: Parse Test Targets
      id: parse
      shell: bash
      run: |
        # Use simple cat + jq to read static resource
        test_targets_json=$(cat dotgithub/resources/test_targets.json)
        # Ensure it's compact JSON string
        test_targets_json=$(echo "$test_targets_json" | jq -c .)
        echo "test_targets_json=$test_targets_json" >> $GITHUB_OUTPUT
        
        count=$(echo "$test_targets_json" | jq '. | length')
        echo "test_targets_count=$count" >> $GITHUB_OUTPUT
