name: Process Test Results
description: Uploads test results to DataDog.
runs:
  using: "composite"
  steps:

    - name: Set Output
      id: set-output
      if: always()
      run: |
        set -x
        echo "test_targets=$(ls results/*log.txt | jq -R . | jq -sc .)" >> $GITHUB_OUTPUT
      shell: bash

outputs:
  test_targets:
    description: The test targets
    value: ${{ steps.set-output.outputs.test_targets }}
