name: On Host Test
description: Runs on-host tests.
inputs:
  os:
    description: "Host OS"
    required: true
runs:
  steps:
    - name: Test
      shell: bash
      run: echo "Test"

    - name: Archive unit test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: unit-test-results
        path: unit-test-results/
